
//Reflect metadata keys
export const HTTP_ROUTE = 'HTTP::ROUTE'
export const HTTP_CONTROLLER = 'HTTP::CONTROLLER'
export const HTTP_MIDDLEWARE = 'HTTP::MIDDLEWARE'
export const IO_LISTENER = 'IO::LISTENER'
export const IO_HANDLER = 'IO::HANDLER'
export const NAMESPACE_IOMIDDLEWARE = 'IO::NAMESPACE::MIDDLEWARE'
export const IO_EVENT_MIDDLEWARE = 'IO::MIDDLEWARE'
export const NEO_MVC_MODEL = 'MVC::MODEL'
export const INJECTABLE_OBJECT = 'CLASS::DI'
export const INTERCEPTABLE = 'CLASS::MODIFY'
export const NEO_SERVICE = 'CLASS::SERVICE'